server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mcart
    username: mcart_user
    password: str0ngP@ss
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
    show-sql: true